// ─────────────────────────────────────────────────────────────────────────────
//  masterdata.js — Central seed data for the Master module
//  Contains: SEEDED_KARIGARS, SEEDED_ITEMS
// ─────────────────────────────────────────────────────────────────────────────

// ── SVG Placeholder Generators ────────────────────────────────────────────────

/** Generate a circular avatar with initials */
const makeAvatar = (initials, bg) => {
  const svg = `<svg width="80" height="80" xmlns="http://www.w3.org/2000/svg"><circle cx="40" cy="40" r="40" fill="${bg}"/><text x="40" y="52" font-family="Arial,sans-serif" font-size="26" font-weight="bold" fill="white" text-anchor="middle">${initials}</text></svg>`;
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
};

/** Generate an Aadhaar card placeholder image (pure ASCII only) */
const makeAadhar = (name, number, bg = '#1a237e') => {
  const short = name.length > 16 ? name.slice(0, 15) + '.' : name;
  const svg = [
    `<svg width="220" height="130" xmlns="http://www.w3.org/2000/svg">`,
    `<rect width="220" height="130" rx="10" fill="${bg}"/>`,
    `<rect x="0" y="0" width="220" height="28" rx="10" fill="rgba(0,0,0,0.25)"/>`,
    `<rect x="0" y="18" width="220" height="10" fill="rgba(0,0,0,0.25)"/>`,
    `<text x="110" y="19" font-family="Arial,sans-serif" font-size="8" fill="#c5cae9" text-anchor="middle" font-weight="bold">GOVERNMENT OF INDIA</text>`,
    `<text x="12" y="48" font-family="Arial,sans-serif" font-size="16" fill="#ffd740" font-weight="bold">AADHAAR</text>`,
    `<rect x="12" y="58" width="44" height="52" rx="4" fill="rgba(255,255,255,0.1)"/>`,
    `<circle cx="34" cy="76" r="14" fill="rgba(255,255,255,0.2)"/>`,
    `<text x="34" y="80" font-family="Arial,sans-serif" font-size="9" fill="white" text-anchor="middle">PHOTO</text>`,
    `<text x="64" y="72" font-family="Arial,sans-serif" font-size="11" fill="white" font-weight="bold">${short}</text>`,
    `<text x="64" y="87" font-family="Arial,sans-serif" font-size="9" fill="#c5cae9">DOB: 01/01/1985  Male</text>`,
    `<text x="12" y="122" font-family="Arial,sans-serif" font-size="14" fill="white" font-weight="bold" letter-spacing="2">${number}</text>`,
    `</svg>`,
  ].join('');
  return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
};

// ── Avatar colours (10, cycling) ──────────────────────────────────────────────
const C = ['#F59E0B', '#EF4444', '#10B981', '#3B82F6', '#8B5CF6', '#F97316', '#EC4899', '#14B8A6', '#6366F1', '#84CC16'];

// ── Karigar Details Seed Data ─────────────────────────────────────────────────
export const SEEDED_KARIGARS = [
  {
    "id": "KR-001",
    "karigarCode": "99204 92403",
    "name": "RISHABH ANTIQUE BMY",
    "number": "99204 92403",
    "email": "rishabh.antique.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2001 3001 1001",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-002",
    "karigarCode": "BJ",
    "name": "BIKASH JANA",
    "number": "8017426927",
    "email": "bikash.jana@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2002 3002 1002",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-003",
    "karigarCode": "KG003",
    "name": "MV JEW BMY",
    "number": "80804 46999",
    "email": "mv.jew.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2003 3003 1003",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-004",
    "karigarCode": "8452914875",
    "name": "MY GOLD BMY",
    "number": "8452914875",
    "email": "my.gold.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2004 3004 1004",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-005",
    "karigarCode": "+91 94255 13599",
    "name": "S VS RPR",
    "number": "+91 94255 13599",
    "email": "s.vs.rpr@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2005 3005 1005",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-006",
    "karigarCode": "91 99203 69424",
    "name": "SWARN MANGAL BMY",
    "number": "91 99203 69424",
    "email": "swarn.mangal.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2006 3006 1006",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-007",
    "karigarCode": "+91 94274 24630",
    "name": "AJAY RAJKOT",
    "number": "+91 94274 24630",
    "email": "ajay.rajkot@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2007 3007 1007",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-008",
    "karigarCode": "KG008",
    "name": "RM",
    "number": "",
    "email": "rm@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2008 3008 1008",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-009",
    "karigarCode": "KG009",
    "name": "SUMIT ORO",
    "number": "91 81039 26955",
    "email": "sumit.oro@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2009 3009 1009",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-010",
    "karigarCode": "KG010",
    "name": "MAITY G",
    "number": "",
    "email": "maity.g@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2010 3010 1010",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-011",
    "karigarCode": "KG011",
    "name": "SRK",
    "number": "",
    "email": "srk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2011 3011 1011",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-012",
    "karigarCode": "KG012",
    "name": "JAI GULAB",
    "number": "",
    "email": "jai.gulab@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2012 3012 1012",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-013",
    "karigarCode": "KG013",
    "name": "IMB",
    "number": "",
    "email": "imb@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2013 3013 1013",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-014",
    "karigarCode": "KG014",
    "name": "MUSKAN ORNAMENT",
    "number": "",
    "email": "muskan.ornament@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2014 3014 1014",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-015",
    "karigarCode": "KG015",
    "name": "JF SHIVAM",
    "number": "",
    "email": "jf.shivam@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2015 3015 1015",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-016",
    "karigarCode": "KG016",
    "name": "UJJAL KARIGAR ANTIQUE",
    "number": "+91 70454 78591",
    "email": "ujjal.karigar.antique@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2016 3016 1016",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-017",
    "karigarCode": "KG017",
    "name": "BHAVIN JEW SANGHVI",
    "number": "",
    "email": "bhavin.jew.sanghvi@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2017 3017 1017",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-018",
    "karigarCode": "KG018",
    "name": "SUJATA GOLD BMY",
    "number": "",
    "email": "sujata.gold.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2018 3018 1018",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-019",
    "karigarCode": "KG019",
    "name": "SRISHTI CHAIN",
    "number": "",
    "email": "srishti.chain@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2019 3019 1019",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-020",
    "karigarCode": "LOCAL CASTING",
    "name": "LOCAL CASTING",
    "number": "",
    "email": "local.casting@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2020 3020 1020",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-021",
    "karigarCode": "KG021",
    "name": "CLASSIC ORNAMENT",
    "number": "",
    "email": "classic.ornament@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2021 3021 1021",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-022",
    "karigarCode": "KG022",
    "name": "SKY CHAIN",
    "number": "",
    "email": "sky.chain@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2022 3022 1022",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-023",
    "karigarCode": "D81",
    "name": "SANJAY HAZRA",
    "number": "9836152482",
    "email": "sanjay.hazra@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2023 3023 1023",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-024",
    "karigarCode": "SJ",
    "name": "CL SURAJIT JANA",
    "number": "8348720338",
    "email": "cl.surajit.jana@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2024 3024 1024",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-025",
    "karigarCode": "KG025",
    "name": "JEWER ORNAMENT",
    "number": "",
    "email": "jewer.ornament@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2025 3025 1025",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-026",
    "karigarCode": "KG026",
    "name": "ZAR",
    "number": "",
    "email": "zar@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2026 3026 1026",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-027",
    "karigarCode": "KG027",
    "name": "STOCK",
    "number": "",
    "email": "stock@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2027 3027 1027",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-028",
    "karigarCode": "KG028",
    "name": "SHARDA",
    "number": "",
    "email": "sharda@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2028 3028 1028",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-029",
    "karigarCode": "M ART",
    "name": "M ART",
    "number": "",
    "email": "m.art@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2029 3029 1029",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-030",
    "karigarCode": "KG030",
    "name": "MANOJ JEW BMY",
    "number": "9820679717",
    "email": "manoj.jew.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2030 3030 1030",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-031",
    "karigarCode": "KG031",
    "name": "LESHYA KM",
    "number": "",
    "email": "leshya.km@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2031 3031 1031",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-032",
    "karigarCode": "KG032",
    "name": "VIKASH KARIGAR",
    "number": "+91 99624 09016",
    "email": "vikash.karigar@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2032 3032 1032",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-033",
    "karigarCode": "KG033",
    "name": "SBR GOLD & ART",
    "number": "",
    "email": "sbr.gold.&.art@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2033 3033 1033",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-034",
    "karigarCode": "KG034",
    "name": "Digvijay",
    "number": "9373124660",
    "email": "digvijay@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2034 3034 1034",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-035",
    "karigarCode": "KG035",
    "name": "DAGINA",
    "number": "",
    "email": "dagina@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2035 3035 1035",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-036",
    "karigarCode": "KG036",
    "name": "SOLID GOLD",
    "number": "",
    "email": "solid.gold@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2036 3036 1036",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-037",
    "karigarCode": "KG037",
    "name": "AD GOLD",
    "number": "",
    "email": "ad.gold@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2037 3037 1037",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-038",
    "karigarCode": "KG038",
    "name": "NAVNATH",
    "number": "",
    "email": "navnath@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2038 3038 1038",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-039",
    "karigarCode": "KG039",
    "name": "DAREWALA",
    "number": "",
    "email": "darewala@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2039 3039 1039",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-040",
    "karigarCode": "KG040",
    "name": "MOTICHAND",
    "number": "",
    "email": "motichand@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2040 3040 1040",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-041",
    "karigarCode": "KG041",
    "name": "ROHIT GOLD",
    "number": "7506841109",
    "email": "rohit.gold@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2041 3041 1041",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-042",
    "karigarCode": "KG042",
    "name": "RISHABH GOLD BMY",
    "number": "9867053615",
    "email": "rishabh.gold.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2042 3042 1042",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-043",
    "karigarCode": "KG043",
    "name": "SR CHAIN",
    "number": "",
    "email": "sr.chain@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2043 3043 1043",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-044",
    "karigarCode": "D145",
    "name": "CL SBPS",
    "number": "",
    "email": "cl.sbps@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2044 3044 1044",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-045",
    "karigarCode": "D21",
    "name": "CL RANJAN JANA",
    "number": "",
    "email": "cl.ranjan.jana@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2045 3045 1045",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-046",
    "karigarCode": "1",
    "name": "READY DELIVERY",
    "number": "7049888822",
    "email": "ready.delivery@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2046 3046 1046",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-047",
    "karigarCode": "D8",
    "name": "MALAY HAJRA",
    "number": "",
    "email": "malay.hajra@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2047 3047 1047",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-048",
    "karigarCode": "AJ",
    "name": "ARUNANSU DAS",
    "number": "",
    "email": "arunansu.das@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2048 3048 1048",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-049",
    "karigarCode": "KG049",
    "name": "DEBASHISH",
    "number": "8319467283",
    "email": "debashish@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2049 3049 1049",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-050",
    "karigarCode": "KG050",
    "name": "BISWANATH",
    "number": "7999049457",
    "email": "biswanath@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2050 3050 1050",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-051",
    "karigarCode": "KG051",
    "name": "NETRAM",
    "number": "",
    "email": "netram@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2051 3051 1051",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-052",
    "karigarCode": "KG052",
    "name": "G KANJI",
    "number": "9131224627",
    "email": "g.kanji@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2052 3052 1052",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-053",
    "karigarCode": "KG053",
    "name": "MATRA SMRUTI",
    "number": "",
    "email": "matra.smruti@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2053 3053 1053",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-054",
    "karigarCode": "KG054",
    "name": "M RAJKOT",
    "number": "9510902129",
    "email": "m.rajkot@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2054 3054 1054",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-055",
    "karigarCode": "KG055",
    "name": "SB GOLD",
    "number": "8828128691",
    "email": "sb.gold@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2055 3055 1055",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-056",
    "karigarCode": "KG056",
    "name": "HEERA JEW",
    "number": "7503206801",
    "email": "heera.jew@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2056 3056 1056",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-057",
    "karigarCode": "KG057",
    "name": "MANIBHATRA BMY",
    "number": "",
    "email": "manibhatra.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2057 3057 1057",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-058",
    "karigarCode": "KG058",
    "name": "SHUBHAS PANJA",
    "number": "6263755158",
    "email": "shubhas.panja@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2058 3058 1058",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-059",
    "karigarCode": "KG059",
    "name": "AJAY RKT",
    "number": "",
    "email": "ajay.rkt@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2059 3059 1059",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-060",
    "karigarCode": "KG060",
    "name": "MOHNISH RKT",
    "number": "",
    "email": "mohnish.rkt@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2060 3060 1060",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-061",
    "karigarCode": "KG061",
    "name": "NIRMAL JI BMY",
    "number": "8655502322",
    "email": "nirmal.ji.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2061 3061 1061",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-062",
    "karigarCode": "KG062",
    "name": "PUNJAB GOLD",
    "number": "9814974907",
    "email": "punjab.gold@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2062 3062 1062",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-063",
    "karigarCode": "KG063",
    "name": "GYS",
    "number": "",
    "email": "gys@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2063 3063 1063",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-064",
    "karigarCode": "KG064",
    "name": "RISHABH BMY",
    "number": "9323791917",
    "email": "rishabh.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2064 3064 1064",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-065",
    "karigarCode": "BMY 01",
    "name": "ACTION GOLD BMY",
    "number": "8689888883",
    "email": "action.gold.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2065 3065 1065",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-066",
    "karigarCode": "CL18",
    "name": "Asthika CL",
    "number": "9903049218",
    "email": "asthika.cl@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2066 3066 1066",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-067",
    "karigarCode": "KG067",
    "name": "VIBHASH",
    "number": "7021192695",
    "email": "vibhash@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2067 3067 1067",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-068",
    "karigarCode": "KG068",
    "name": "TRIDEV",
    "number": "7440844308",
    "email": "tridev@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2068 3068 1068",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-069",
    "karigarCode": "KG069",
    "name": "C L OFFICE",
    "number": "8100147110",
    "email": "c.l.office@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2069 3069 1069",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-070",
    "karigarCode": "KG070",
    "name": "DHRUVIL CREATION",
    "number": "9833235994",
    "email": "dhruvil.creation@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2070 3070 1070",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-071",
    "karigarCode": "KG071",
    "name": "ANAND JI KOLAPUR",
    "number": "9665815024",
    "email": "anand.ji.kolapur@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2071 3071 1071",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-072",
    "karigarCode": "KG072",
    "name": "NIRWAAN",
    "number": "9136030916",
    "email": "nirwaan@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2072 3072 1072",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-073",
    "karigarCode": "KG073",
    "name": "DEREWALA",
    "number": "8866953411",
    "email": "derewala@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2073 3073 1073",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-074",
    "karigarCode": "KG074",
    "name": "VEER",
    "number": "9833725566",
    "email": "veer@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2074 3074 1074",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-075",
    "karigarCode": "KG075",
    "name": "BHAVIKA",
    "number": "9820383840",
    "email": "bhavika@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2075 3075 1075",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-076",
    "karigarCode": "KG076",
    "name": "JOY GURU",
    "number": "9330984637",
    "email": "joy.guru@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2076 3076 1076",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-077",
    "karigarCode": "KG077",
    "name": "VK",
    "number": "9081743200",
    "email": "vk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2077 3077 1077",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-078",
    "karigarCode": "KG078",
    "name": "AURAM",
    "number": "8719930003",
    "email": "auram@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2078 3078 1078",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-079",
    "karigarCode": "KG079",
    "name": "MUKESH ART",
    "number": "9004648954",
    "email": "mukesh.art@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2079 3079 1079",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-080",
    "karigarCode": "KG080",
    "name": "DILIP GHOSH",
    "number": "8871588456",
    "email": "dilip.ghosh@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2080 3080 1080",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-081",
    "karigarCode": "KG081",
    "name": "R V",
    "number": "7779029864",
    "email": "r.v@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2081 3081 1081",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-082",
    "karigarCode": "KG082",
    "name": "VNK",
    "number": "9820026696",
    "email": "vnk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2082 3082 1082",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-083",
    "karigarCode": "KG083",
    "name": "SHREE SHYAM GOLD",
    "number": "9983906966",
    "email": "shree.shyam.gold@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2083 3083 1083",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-084",
    "karigarCode": "KG084",
    "name": "Chandra Varsha",
    "number": "9869587283",
    "email": "chandra.varsha@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2084 3084 1084",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-085",
    "karigarCode": "KG085",
    "name": "MEET",
    "number": "97838 4348",
    "email": "meet@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2085 3085 1085",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-086",
    "karigarCode": "SWASTIK CREATION",
    "name": "SWASTIK CREATION",
    "number": "9664833686",
    "email": "swastik.creation@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2086 3086 1086",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-087",
    "karigarCode": "KG087",
    "name": "YUG",
    "number": "9712056561",
    "email": "yug@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2087 3087 1087",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-088",
    "karigarCode": "KG088",
    "name": "SABRI KT",
    "number": "9442222221",
    "email": "sabri.kt@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2088 3088 1088",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-089",
    "karigarCode": "KG089",
    "name": "R MILAN BMY",
    "number": "9324162408",
    "email": "r.milan.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2089 3089 1089",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-090",
    "karigarCode": "KG090",
    "name": "PB",
    "number": "7389599035",
    "email": "pb@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2090 3090 1090",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-091",
    "karigarCode": "KG091",
    "name": "RK",
    "number": "7999615824",
    "email": "rk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2091 3091 1091",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-092",
    "karigarCode": "P93",
    "name": "PIYUSH DMD",
    "number": "8586818393",
    "email": "piyush.dmd@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2092 3092 1092",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-093",
    "karigarCode": "BB75",
    "name": "BRAMHAND BMY",
    "number": "7987555077",
    "email": "bramhand.bmy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2093 3093 1093",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-094",
    "karigarCode": "KG094",
    "name": "RM",
    "number": "9993265337",
    "email": "rm@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2094 3094 1094",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-095",
    "karigarCode": "81",
    "name": "NB",
    "number": "",
    "email": "nb@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2095 3095 1095",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-096",
    "karigarCode": "A50",
    "name": "SAHEB",
    "number": "8120640527",
    "email": "saheb@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2096 3096 1096",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-097",
    "karigarCode": "A12",
    "name": "SP",
    "number": "9340681720",
    "email": "sp@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2097 3097 1097",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-098",
    "karigarCode": "A6",
    "name": "SKS",
    "number": "9691697046",
    "email": "sks@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2098 3098 1098",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-099",
    "karigarCode": "A57",
    "name": "LK",
    "number": "8871556190",
    "email": "lk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2099 3099 1099",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-100",
    "karigarCode": "A2",
    "name": "AK",
    "number": "7489998885",
    "email": "ak@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2100 3100 1100",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-101",
    "karigarCode": "A52",
    "name": "JP",
    "number": "9755296223",
    "email": "jp@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2101 3101 1101",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-102",
    "karigarCode": "A54",
    "name": "SKA",
    "number": "9475419168",
    "email": "ska@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2102 3102 1102",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-103",
    "karigarCode": "A56",
    "name": "PK",
    "number": "9769585315",
    "email": "pk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2103 3103 1103",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-104",
    "karigarCode": "A48",
    "name": "CK",
    "number": "9479272011",
    "email": "ck@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2104 3104 1104",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-105",
    "karigarCode": "G009",
    "name": "GOVIND JI",
    "number": "1234567890",
    "email": "govind.ji@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2105 3105 1105",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-106",
    "karigarCode": "A51",
    "name": "SS",
    "number": "9589383737",
    "email": "ss@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2106 3106 1106",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-107",
    "karigarCode": "A42",
    "name": "JK",
    "number": "8871302028",
    "email": "jk@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2107 3107 1107",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-108",
    "karigarCode": "JC",
    "name": "JEWELS CREATION",
    "number": "",
    "email": "jewels.creation@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2108 3108 1108",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-109",
    "karigarCode": "TD",
    "name": "CL TARAK DUTTA",
    "number": "",
    "email": "cl.tarak.dutta@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2109 3109 1109",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-110",
    "karigarCode": "SR",
    "name": "SALES RETURN/TAG DIFFERENCE",
    "number": "",
    "email": "sales.return/tag.difference@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2110 3110 1110",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-111",
    "karigarCode": "AJO",
    "name": "AT RAIPUR (WHOLESALE) (AJO)",
    "number": "",
    "email": "at.raipur.(wholesale).(ajo)@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2111 3111 1111",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-112",
    "karigarCode": "D202",
    "name": "CL ANIL KUMAR DHAR(KA) & GITA DHAR",
    "number": "",
    "email": "cl.anil.kumar.dhar(ka).&.gita.dhar@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2112 3112 1112",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-113",
    "karigarCode": "D30",
    "name": "CL BIKASH BERA",
    "number": "",
    "email": "cl.bikash.bera@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2113 3113 1113",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-114",
    "karigarCode": "D30",
    "name": "CL Bidyut Bera",
    "number": "",
    "email": "cl.bidyut.bera@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2114 3114 1114",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-115",
    "karigarCode": "SP",
    "name": "SHAMAL PAUL",
    "number": "",
    "email": "shamal.paul@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2115 3115 1115",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-116",
    "karigarCode": "D100",
    "name": "CL SHRI GANNAYAK JEWELLERS(KAILASH JI)",
    "number": "",
    "email": "cl.shri.gannayak.jewellers(kailash.ji)@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2116 3116 1116",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-117",
    "karigarCode": "D100",
    "name": "CL SHRI GANNAYAK JEWELLERS(KAILASH JI)",
    "number": "",
    "email": "cl.shri.gannayak.jewellers(kailash.ji)@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2117 3117 1117",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-118",
    "karigarCode": "D175",
    "name": "CL SURESH PAL & JEWELLERS(SURESH PAL)",
    "number": "",
    "email": "cl.suresh.pal.&.jewellers(suresh.pal)@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2118 3118 1118",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-119",
    "karigarCode": "D45",
    "name": "CL DIBAKAR SAHOO",
    "number": "",
    "email": "cl.dibakar.sahoo@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2119 3119 1119",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-120",
    "karigarCode": "D116",
    "name": "CL RAM DHAN",
    "number": "",
    "email": "cl.ram.dhan@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2120 3120 1120",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-121",
    "karigarCode": "D41",
    "name": "AMAR MAJI",
    "number": "",
    "email": "amar.maji@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2121 3121 1121",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-122",
    "karigarCode": "D220",
    "name": "CL MANOHAR ALI",
    "number": "",
    "email": "cl.manohar.ali@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2122 3122 1122",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-123",
    "karigarCode": "D120",
    "name": "CL M J JEWELLERS (JAYANTA DAS )",
    "number": "",
    "email": "cl.m.j.jewellers.(jayanta.das.)@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2123 3123 1123",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-124",
    "karigarCode": "D109",
    "name": "CL ANITA NARENDRA SUNALIA (MANISH KUMAR SONALIA)",
    "number": "",
    "email": "cl.anita.narendra.sunalia.(manish.kumar.sonalia)@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2124 3124 1124",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-125",
    "karigarCode": "PJ",
    "name": "CL PRADEEP JAMUWAL",
    "number": "",
    "email": "cl.pradeep.jamuwal@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2125 3125 1125",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-126",
    "karigarCode": "D38",
    "name": "CL SAMIR DHARA",
    "number": "",
    "email": "cl.samir.dhara@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2126 3126 1126",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-127",
    "karigarCode": "D240",
    "name": "CL ASHISH INTERNATIONAL (ASHISH) JI",
    "number": "",
    "email": "cl.ashish.international.(ashish).ji@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2127 3127 1127",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-128",
    "karigarCode": "D8A",
    "name": "CL SUJAN ROY",
    "number": "",
    "email": "cl.sujan.roy@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2128 3128 1128",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-129",
    "karigarCode": "D11",
    "name": "CL DINESH CHANDRA MANDAN(CHANDRA PRAKASH MANDAN",
    "number": "",
    "email": "cl.dinesh.chandra.mandan(chandra.prakash.mandan@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2129 3129 1129",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-130",
    "karigarCode": "D1A",
    "name": "CL SURESH SONILIYA",
    "number": "",
    "email": "cl.suresh.soniliya@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2130 3130 1130",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-131",
    "karigarCode": "D5",
    "name": "CL GAURAV SONI & VIKAS SONI",
    "number": "",
    "email": "cl.gaurav.soni.&.vikas.soni@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Factory",
    "aadharNumber": "2131 3131 1131",
    "verifyBy": "Admin"
  },
  {
    "id": "KR-132",
    "karigarCode": "1",
    "name": "Muskseed",
    "number": "8720070003",
    "email": "muskseed@gmail.com",
    "address": "Raipur, Chhattisgarh",
    "type": "Office",
    "aadharNumber": "2132 3132 1132",
    "verifyBy": "Admin"
  }
];
